### ISSUE TITLE
WARN:amqp::channel: basic_publish(mandatory=true) failures are not handled and result in blocked channels!

### ISSUE THREAD

**Issue by thomas-tran** [subzerocloud/pg-amqp-bridge#28]
I am keep getting this message when trigger the on_row_change function

![image](https://user-images.githubusercontent.com/5725085/111701127-797e8380-888e-11eb-878d-86809619cf98.png)

**Comment by ruslantalpa** [comment]
it comes from the amqp lib that is used and it's not a error, it's a warning
https://github.com/Antti/rust-amqp/blob/master/src/channel.rs#L352
you see it only when you set the logging mode to debug.
it does not mean an error happened, it means, if an error would happen, the lib will not handle the error, and that is ok because 
here we check for an error
https://github.com/subzerocloud/pg-amqp-bridge/blob/master/src/lib.rs#L99
and try to resend the message
